#!/usr/bin/env node
'use strict';

/**
 * build_site.js — bundle the card generators for the browser.
 *
 * The site renders live previews using the *same* modules CI renders with, so a
 * preview can never drift from what actually lands on someone's profile. That
 * only works because the generators are pure string builders: no DOM, no fs, no
 * network. This wraps them in the smallest possible CommonJS loader.
 *
 * Three Node builtins get reached transitively and are stubbed rather than
 * removed, because the code paths that touch them are all failure paths that
 * already fall back to defaults:
 *
 *   path   constants.js builds absolute paths at module load
 *   fs     config.js reads grub.config.json; ENOENT means "use the defaults",
 *          which in a browser is exactly right
 *   child_process  github.js shells out to git; never called from a generator
 *
 * Still zero dependencies — no bundler, no transpiler, no package.json.
 *
 * Usage:
 *   node scripts/build_site.js            # write site/grub.browser.js
 *   node scripts/build_site.js --check    # exit 1 if the bundle is stale
 */

const fs = require('fs');
const path = require('path');
const { ROOT } = require('./lib/constants');

const SCRIPTS = path.join(ROOT, 'scripts');
const OUT = path.join(ROOT, 'site', 'grub.browser.js');

// What the site actually calls. Everything else is pulled in by following
// requires, so adding a card needs no change here.
const ENTRIES = {
  components: './generators/index',
  palette: './lib/palette',
  copy: './lib/copy',
  snacks: './lib/snacks',
  config: './lib/config',
  mood: './lib/mood',
  svg: './lib/svg',
};

const BUILTINS = new Set(['fs', 'path', 'child_process']);

/** Resolve a require id against the module doing the requiring. */
function resolve(fromId, id) {
  if (BUILTINS.has(id)) return id;
  const parts = `${path.posix.dirname(fromId)}/${id}`.split('/');
  const out = [];
  for (const p of parts) {
    if (p === '..') out.pop();
    else if (p !== '.' && p !== '') out.push(p);
  }
  return `./${out.join('/')}`;
}

const modules = new Map();

function collect(id) {
  if (modules.has(id) || BUILTINS.has(id)) return;
  const file = path.join(SCRIPTS, `${id.replace(/^\.\//, '')}.js`);
  if (!fs.existsSync(file)) throw new Error(`cannot resolve ${id} (looked for ${file})`);
  const src = fs.readFileSync(file, 'utf8');
  modules.set(id, src);
  for (const m of src.matchAll(/require\(\s*'([^']+)'\s*\)/g)) collect(resolve(id, m[1]));
}

for (const id of Object.values(ENTRIES)) collect(id);

const factories = [...modules].map(([id, src]) =>
  // eslint-disable-next-line prefer-template
  `${JSON.stringify(id)}: function (module, exports, require, __dirname, __filename) {\n${src}\n}`);

const bundle = `/* Generated by scripts/build_site.js — do not edit.
 * ${modules.size} modules from scripts/, the same ones the Action renders with.
 */
(function () {
  'use strict';

  var FACTORIES = {
${factories.join(',\n')}
  };

  var CACHE = {};

  // Enough of each builtin for module *load* to succeed. Anything that would
  // actually need Node throws or reports "missing", which every caller in the
  // render path already handles by falling back to a default.
  var SHIMS = {
    path: {
      resolve: function () { return Array.prototype.join.call(arguments, '/'); },
      join: function () { return Array.prototype.join.call(arguments, '/'); },
      dirname: function (p) { return String(p).replace(/\\/[^/]*$/, ''); },
    },
    fs: {
      readFileSync: function () { var e = new Error('no filesystem'); e.code = 'ENOENT'; throw e; },
      existsSync: function () { return false; },
      writeFileSync: function () { throw new Error('no filesystem'); },
      mkdirSync: function () { throw new Error('no filesystem'); },
    },
    child_process: {
      execSync: function () { throw new Error('no child_process'); },
    },
  };

  function resolve(from, id) {
    if (SHIMS[id]) return id;
    var parts = (from.slice(0, from.lastIndexOf('/')) + '/' + id).split('/');
    var out = [];
    for (var i = 0; i < parts.length; i++) {
      if (parts[i] === '..') out.pop();
      else if (parts[i] !== '.' && parts[i] !== '') out.push(parts[i]);
    }
    return './' + out.join('/');
  }

  function load(id) {
    if (SHIMS[id]) return SHIMS[id];
    if (CACHE[id]) return CACHE[id].exports;
    var factory = FACTORIES[id];
    if (!factory) throw new Error('module not bundled: ' + id);
    var mod = CACHE[id] = { exports: {} };
    factory(mod, mod.exports, function (dep) { return load(resolve(id, dep)); }, '/', id);
    return mod.exports;
  }

  window.GRUB = {
${Object.entries(ENTRIES).map(([k, v]) => `    ${k}: load(${JSON.stringify(v)})`).join(',\n')}
  };
}());
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (current === bundle) {
    console.log(`site/grub.browser.js is up to date (${modules.size} modules)`);
    process.exit(0);
  }
  console.error('x site/grub.browser.js is stale — run: node scripts/build_site.js');
  process.exit(1);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, bundle);
console.log(`wrote site/grub.browser.js — ${modules.size} modules, ${(bundle.length / 1024).toFixed(0)} KB`);
console.log(`  ${[...modules.keys()].join(' ')}`);
